
spring:
  profiles:
    active : local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@122.34.228.67:32771/xe?serverTimezone=UTC&characterEncoding=UTF8
    username: com
    password: com123
    hikari:
      maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource
    #url: ENC("WyxbpQpzOp9CFr8qQoX+/kKp72qobgaowQaODNwWYUuUsRbBtOO0geNgB221H+1T/PzTDNIM4T/Se57CGgELwDcMZb+0gMhdYuX4R4ImafwFTNcLa0EVfCT6r/1Bd8qBpfpvjxh+9FbTWKmOkvO/3Q=="")
    #username: ENC("dB/dWpdKtt8R3lJiVwRgDm0EiKUqbf30aGqTFaxWyEQ=")
    #password: ENC("9lf6+nCB8rTPfyIXu9ye4dMBve0FkqTwF7oBIDLMoA8=")
  devtools:
    restart:
      enabled: true
      poll-interval: 2
      quiet-period: 1
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
#  jmx:
#    enabled: true
#management:
#  endpoints:
#    jmx:
#      exposure:
#        include: "*"
# HTML 형식의 swagger 문서의 사용자 경로 지정
springdoc:
  api-docs:
    path: /api-docs/kpcm # 전체 API 정보를 가져오는 REST API
  packages-to-scan: kp  #api가 정의된 package 검색경로
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8  
  swagger-ui:
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    groups-order: DESC # path, query, body, response 순으로 출력
    disable-swagger-default-url: true
    #path: /swagger-ui.html  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    doc-expansion: none  
    
  paths-to-match:
    - /** # swagger-ui에 표시할 api의 엔드포인트 패턴    

jasypt:
  encryptor:
    bean: jasyptEncryptor
server:
  servlet:
    context-path: /
  port: 8090
  tomcat:
    connection-timeout: 20s
#logging:
#  level:
#    root: DEBUG
knwp:
  upload-path: 'C:\\temp\\'
  jedis-path: 'localhost'
  jedis-port: 6379
---
spring:
  config:
     activate:
        on-profile: local

