
spring:
  profiles:
    active : local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@122.34.228.67:32771/xe?serverTimezone=UTC&characterEncoding=UTF8
    username: com
    password: com123
    hikari:
      maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource
    #url: ENC("WyxbpQpzOp9CFr8qQoX+/kKp72qobgaowQaODNwWYUuUsRbBtOO0geNgB221H+1T/PzTDNIM4T/Se57CGgELwDcMZb+0gMhdYuX4R4ImafwFTNcLa0EVfCT6r/1Bd8qBpfpvjxh+9FbTWKmOkvO/3Q=="")
    #username: ENC("dB/dWpdKtt8R3lJiVwRgDm0EiKUqbf30aGqTFaxWyEQ=")
    #password: ENC("9lf6+nCB8rTPfyIXu9ye4dMBve0FkqTwF7oBIDLMoA8=")
  devtools:
    restart:
      enabled: true
      poll-interval: 2
      quiet-period: 1
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
#  jmx:
#    enabled: true
#management:
#  endpoints:
#    jmx:
#      exposure:
#        include: "*"

springdoc:
  api-docs:
    path: /api-docs/kpcm # api-docs url: localhost:8090/api-docs
    groups:
      enabled: true # group 허용
  swagger-ui:
    path: /index.html # swagger url : localhost:8090/swagger-ui/index.html
    enabled: true
    groups-order: ASC # group 정렬 오름차순
    tags-sorter: alpha # tag 정렬 알파벳순
    operations-sorter: alpha # api 정렬 알파벳순
    display-request-duration: true
    doc-expansion: none # swagger tag 리스트 펼치기
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true	# returnType ModelAndView도 Swagger에 노출
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

jasypt:
  encryptor:
    bean: jasyptEncryptor
server:
  servlet:
    context-path: /
  port: 8090
  tomcat:
    connection-timeout: 20s
#logging:
#  level:
#    root: DEBUG
knwp:
  upload-path: 'C:\\temp\\'
  jedis-path: 'localhost'
  jedis-port: 6379
---
spring:
  config:
    activate:
      on-profile: local

